database:
  driverClass: org.postgresql.Driver
  user: ${DB_USERNAME:-postgres}
  password: ${DB_PASSWORD:-postgres}
  url: jdbc:postgresql://${DB_HOST:-localhost:5432}/${DB_NAME:-postgres}
  properties:
    charSet: UTF-8
    hibernate.hbm2ddl.auto: validate
    hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
  validationQuery: "SELECT 1"

server:
  rootPath: /api/
  applicationConnectors:
      - type: http
        port: 8080
  adminConnectors:
      - type: http
        port: 8081

keycloakConfiguration:
  realm: ${KC_REALM:-massages}
  auth-server-url: ${KC_SERVER:-http://localhost:9090/auth}
  ssl-required: none
  resource: ${KC_RESOURCE:-api-client}
  bearer-only: true
  enable-cors: true
  credentials:
    secret: ${KC_SECRET:-b4a1ee69-6441-49a0-b653-e2875234c0ef}

smtpConfiguration:
  applicationUrl: ${SMTP_APP_URL:-http://localhost:8080}
  server: ${SMTP_SERVER:-localhost}
  port: ${SMTP_PORT:-587}
  username: ${SMTP_USERNAME}
  password: ${SMTP_PASSWORD}
  fromEmail: ${SMTP_FROM_EMAIL:-portal@massages.com}
  fromName: ${SMTP_FROM_NAME:-admin}
